version: "3.1"

services:
  database:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: test_database
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: database
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: a

  server:
    build: "./server"
    volumes:
      - ./server:/home/node/app
    ports:
      - 8501:8080
    depends_on:
      - database

  client:
    build: "./client"
    volumes:
      - ./client:/home/node/app
    ports:
      - 8500:3000
    depends_on:
      - server
